version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend/Output:/app/backend/Output  # Persist output files
      - ./backend/data:/app/backend/data      # Mount data directory for input files
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - OUTPUT_FOLDER=/app/backend/Output
    restart: unless-stopped
